export const CLOUD_TERMS: Record<string, string> = {
  'EC2': 'Amazon EC2 — Virtual computers you rent by the hour. Like renting a laptop in the cloud instead of buying one.',
  'S3': 'Amazon S3 — Cloud storage for files. Like a hard drive in the sky that never gets full.',
  'RDS': 'Amazon RDS — A managed database service. Amazon runs your database for you so you don\'t have to.',
  'Lambda': 'AWS Lambda — Code that runs only when needed. You pay per use, not per hour. Great for saving money.',
  'CloudWatch': 'AWS CloudWatch — Monitoring service that watches your cloud resources and alerts you when something goes wrong.',
  'IAM': 'Identity and Access Management — Controls who can access what in your cloud. Like a security badge system.',
  'VPC': 'Virtual Private Cloud — Your own private section of AWS, isolated from other customers. Like your own floor in a shared office building.',
  'NAT Gateway': 'Allows resources in your private network to access the internet without being directly exposed to it.',
  'EBS': 'Elastic Block Storage — Hard drives attached to your EC2 virtual computers. Deleted separately from the computer.',
  'CloudFront': 'Amazon\'s global content delivery network. Serves your website from locations close to each visitor for faster loading.',
  'Route 53': 'Amazon\'s DNS service — Translates domain names like mysite.com into IP addresses computers understand.',
  'Elastic IP': 'A fixed public IP address you can attach to your cloud resources. Costs money even when not in use.',
  'Auto Scaling': 'Automatically adds or removes servers based on traffic. Scales up when busy, down when quiet.',
  'Load Balancer': 'Distributes incoming traffic across multiple servers. Prevents any single server from getting overwhelmed.',
  'SQS': 'Amazon Simple Queue Service — A message queue that lets different parts of your app communicate asynchronously.',
  'SNS': 'Amazon Simple Notification Service — Sends notifications via email, SMS, or to other services.',
  'DynamoDB': 'Amazon\'s fast NoSQL database. Great for apps needing speed at massive scale.',
  'Kubernetes': 'An open-source system for managing containers at scale. Powerful but complex to operate.',
  'Docker': 'Software that packages your application and all its dependencies into a portable container.',
  'Container': 'A lightweight package containing everything needed to run a piece of software consistently anywhere.',
  'Serverless': 'Running code without managing servers. You only pay when your code actually runs.',
  'CDN': 'Content Delivery Network — A network of servers worldwide that deliver content from the location closest to each user.',
  'HIPAA': 'US healthcare data privacy law. Any app handling patient medical records must comply or face large fines.',
  'GDPR': 'European data privacy regulation. Applies to any company handling data of EU residents.',
  'FedRAMP': 'US government cloud security standard. Required for any software used by federal agencies.',
  'SOC 2': 'Security audit certification. Proves your company has proper data security controls in place.',
  'PCI DSS': 'Payment Card Industry standard. Required for any system that processes credit card payments.',
  'Reserved Instance': 'Pay upfront for cloud resources for 1-3 years in exchange for 30-60% discount vs paying hourly.',
  'Spot Instance': 'Spare AWS capacity available at up to 90% discount. Can be interrupted with 2 minutes notice.',
  'Egress': 'Data leaving the cloud. Cloud providers charge for data going out — often an unexpected cost.',
  'Ingress': 'Data coming into the cloud. Usually free — providers charge to bring data in, rarely to send it out.',
  'Multi-cloud': 'Using services from more than one cloud provider simultaneously.',
  'On-premise': 'Software running on your own physical servers in your own building, not in the cloud.',
  'FinOps': 'Financial Operations for cloud — the practice of managing and optimizing cloud costs.',
  'TCO': 'Total Cost of Ownership — the complete cost including hardware, software, staff, and maintenance.',
  'SLA': 'Service Level Agreement — the uptime guarantee a cloud provider promises, usually 99.9% or higher.',
  'Latency': 'The delay between sending a request and receiving a response. Lower is better.',
  'Throughput': 'How much data can be processed in a given time period.',
  'Availability Zone': 'A physically separate data center within a cloud region. Use multiple zones to prevent outages.',
  'Region': 'A geographic area containing multiple data centers. Choose regions close to your users for lower latency.',
  'Terraform': 'A tool for defining cloud infrastructure as code. Write once, deploy anywhere.',
  'DevOps': 'A practice combining software development and IT operations to deliver software faster and more reliably.',
  'CI/CD': 'Continuous Integration and Continuous Deployment — automated testing and deployment of code changes.',
  'Microservices': 'Breaking an application into small independent services that each do one thing well.',
  'API Gateway': 'A managed service that acts as the front door for your application\'s APIs.',
  'Blob Storage': 'Microsoft Azure\'s equivalent of Amazon S3 — cloud file storage.',
  'Azure AD': 'Microsoft\'s identity service — manages who can log into your applications and systems.',
  'GKE': 'Google Kubernetes Engine — Google\'s managed Kubernetes service.',
  'BigQuery': 'Google\'s serverless data warehouse — analyze massive datasets with SQL queries.',
  'Vertex AI': 'Google\'s platform for building and deploying AI and machine learning models.',
  'SageMaker': 'Amazon\'s platform for building training and deploying machine learning models.',
}
