export default function TermsPage() {
  const sections = [
    {
      title: '1. Nature of Service',
      body: [
        'Cloud Intelligence provides AI-powered cloud cost analysis, provider recommendations, and migration planning tools. All output is advisory in nature and does not constitute financial, legal, or professional consulting advice.',
        'Recommendations are generated by large language models using published cloud provider pricing data and industry benchmarks. They reflect general guidance, not a formal audit of your infrastructure.',
      ],
    },
    {
      title: '2. User Responsibility',
      body: [
        'You are solely responsible for verifying any recommendation before acting on it. Cloud pricing, availability, and terms of service change frequently — always confirm figures directly with your cloud provider before making purchasing decisions, architecture changes, or contract commitments.',
        'Cloud Intelligence is not liable for any costs, outages, data loss, or other consequences arising from decisions made based on our output.',
      ],
    },
    {
      title: '3. Billing Data',
      body: [
        'If you upload a cloud bill or connect cloud account credentials, that data is stored securely and used only to generate your analysis. We access billing data in read-only mode and do not modify, share, or sell it.',
        'Uploaded files and credentials are encrypted at rest. You may delete your billing data at any time from your dashboard.',
      ],
    },
    {
      title: '4. Limitation of Liability',
      body: [
        'NOT FINANCIAL OR PROFESSIONAL ADVICE. All output generated by Cloud Intelligence — including cost estimates, provider recommendations, architecture diagrams, migration plans, savings projections, and compliance guidance — is advisory information only. It does not constitute financial advice, legal advice, professional consulting, or any certified audit. No output should be treated as a guarantee of savings or performance.',
        'NO GUARANTEED SAVINGS. Savings estimates are based on industry benchmarks and published cloud pricing. Actual savings depend on your specific workload, usage patterns, negotiated rates, and changes in provider pricing. Cloud Intelligence makes no warranty, express or implied, that any projected savings will be realized.',
        'USER ASSUMES RESPONSIBILITY FOR VERIFICATION. You are solely responsible for independently verifying all recommendations, pricing figures, and technical guidance before acting on them. Cloud provider pricing changes frequently. You must confirm all figures directly with your provider before making purchasing decisions, signing contracts, or committing to architectural changes.',
        'TEST BEFORE PRODUCTION. Any infrastructure changes, migrations, or configuration modifications recommended by this service must be tested in a non-production environment before deployment. Cloud Intelligence is not liable for outages, data loss, cost overruns, or other damages arising from changes made without adequate testing.',
        'To the maximum extent permitted by applicable law, Cloud Intelligence and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages — including lost revenue, lost savings, data loss, service interruptions, or costs of procurement of substitute services — arising from your use of or reliance on this service, even if advised of the possibility of such damages.',
        'Our total aggregate liability for any claim arising from use of the service shall not exceed the amount you paid us in the 12 months preceding the claim, or $100 USD, whichever is greater.',
      ],
    },
    {
      title: '5. Free Tier',
      body: [
        'The free tier includes a limited number of AI analyses per month. Free tier usage may be rate-limited or paused during periods of high demand.',
        'We reserve the right to change the scope of the free tier with 30 days notice. Existing analyses are not deleted when a free tier limit is reached — only new analyses are restricted.',
      ],
    },
    {
      title: '6. Subscriptions',
      body: [
        'Paid subscriptions are billed monthly or annually in advance. You may cancel at any time — cancellation takes effect at the end of the current billing period, and no partial refunds are issued for unused time.',
        'We reserve the right to change subscription pricing with 30 days advance notice to active subscribers. Continued use after that date constitutes acceptance of the new pricing.',
      ],
    },
    {
      title: '7. Acceptable Use',
      body: [
        'You may not use Cloud Intelligence to scrape data, reverse-engineer our models, or resell our output without written permission. Automated access beyond normal use requires a commercial API agreement.',
        'We reserve the right to suspend accounts that we reasonably believe are violating these terms or using the service in a way that harms other users.',
      ],
    },
    {
      title: '8. Changes to Terms',
      body: [
        'We may update these terms from time to time. We will notify registered users by email at least 14 days before material changes take effect. Continued use of the service after that date constitutes acceptance.',
        'The current version of these terms is always available at this URL.',
      ],
    },
    {
      title: '9. Governing Law',
      body: [
        'These terms are governed by the laws of the State of Delaware, United States, without regard to conflict of law principles. Any disputes shall be resolved in the courts of Delaware.',
      ],
    },
  ]

  return (
    <div style={{ minHeight: '100vh', background: '#0a0a0f', color: 'white' }}>
      <div style={{ maxWidth: 720, margin: '0 auto', padding: '100px 24px 80px' }}>

        <div style={{ marginBottom: 48 }}>
          <div style={{
            display: 'inline-block',
            background: 'rgba(99,102,241,0.1)',
            border: '1px solid rgba(99,102,241,0.3)',
            borderRadius: 20, padding: '6px 16px',
            fontSize: 12, color: '#818cf8', fontWeight: 700,
            marginBottom: 16, letterSpacing: 1,
          }}>
            LEGAL
          </div>
          <h1 style={{ fontSize: 'clamp(28px, 5vw, 40px)', fontWeight: 900, marginBottom: 12 }}>
            Terms of Service
          </h1>
          <p style={{ color: '#555', fontSize: 14 }}>
            Last updated: May 1, 2026 · Effective immediately for new users
          </p>
        </div>

        <div style={{
          background: 'rgba(245,158,11,0.08)',
          border: '1px solid rgba(245,158,11,0.2)',
          borderRadius: 12, padding: '16px 20px', marginBottom: 48,
        }}>
          <p style={{ fontSize: 14, color: '#fbbf24', margin: 0, lineHeight: 1.6 }}>
            <strong>Plain English summary:</strong> This service gives you AI-powered cloud cost advice.
            It&apos;s advisory only — not a substitute for professional consulting.
            Always verify recommendations before acting. We store your data securely and never sell it.
          </p>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 36 }}>
          {sections.map(section => (
            <div key={section.title}>
              <h2 style={{ fontSize: 17, fontWeight: 800, color: 'white', marginBottom: 14, paddingBottom: 10, borderBottom: '1px solid rgba(255,255,255,0.06)' }}>
                {section.title}
              </h2>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
                {section.body.map((para, i) => (
                  <p key={i} style={{ fontSize: 14, color: '#a0a0b0', lineHeight: 1.75, margin: 0 }}>
                    {para}
                  </p>
                ))}
              </div>
            </div>
          ))}
        </div>

        <div style={{ marginTop: 56, paddingTop: 32, borderTop: '1px solid rgba(255,255,255,0.06)', display: 'flex', gap: 20, flexWrap: 'wrap' }}>
          <a href="/privacy" style={{ color: '#6366f1', fontSize: 14, textDecoration: 'none', fontWeight: 600 }}>
            Privacy Policy →
          </a>
          <a href="mailto:legal@cloudintelligence.ai" style={{ color: '#555', fontSize: 14, textDecoration: 'none' }}>
            Questions? legal@cloudintelligence.ai
          </a>
        </div>
      </div>
    </div>
  )
}
