export default function TermsPage() {
  const sections = [
    {
      title: '1. Nature of Service',
      body: [
        'Cloud Intelligence provides AI-powered cloud cost analysis, provider recommendations, and migration planning tools. All output is advisory in nature and does not constitute financial, legal, or professional consulting advice.',
        'Some recommendations are generated by a large language model from information you provide. Compute comparisons use selected live AWS and Azure prices with static fallbacks and static references for other providers. These are not a formal audit of your infrastructure.',
      ],
    },
    {
      title: '2. User Responsibility',
      body: [
        'You are solely responsible for verifying any recommendation before acting on it. Cloud pricing, availability, and terms of service change frequently — always confirm figures directly with your cloud provider before making purchasing decisions, architecture changes, or contract commitments.',
        'Cloud Intelligence is not liable for any costs, outages, data loss, or other consequences arising from decisions made based on our output.',
      ],
    },
    {
      title: '3. Billing Data',
      body: [
        'The public app accepts compatible CSV billing files and text input. It parses uploaded CSVs in the browser and sends summarized bill data to the AI service when you request advice.',
        'Direct cloud account connection is not enabled and the public app does not collect AWS access keys. Analyses you choose to save are written to your account in Supabase.',
      ],
    },
    {
      title: '4. Limitation of Liability',
      body: [
        'NOT FINANCIAL OR PROFESSIONAL ADVICE. All output generated by Cloud Intelligence — including cost estimates, provider recommendations, architecture diagrams, migration plans, savings projections, and compliance guidance — is advisory information only. It does not constitute financial advice, legal advice, professional consulting, or any certified audit. No output should be treated as a guarantee of savings or performance.',
        'NO GUARANTEED SAVINGS. Savings estimates are based on industry benchmarks and published cloud pricing. Actual savings depend on your specific workload, usage patterns, negotiated rates, and changes in provider pricing. Cloud Intelligence makes no warranty, express or implied, that any projected savings will be realized.',
        'USER ASSUMES RESPONSIBILITY FOR VERIFICATION. You are solely responsible for independently verifying all recommendations, pricing figures, and technical guidance before acting on them. Cloud provider pricing changes frequently. You must confirm all figures directly with your provider before making purchasing decisions, signing contracts, or committing to architectural changes.',
        'TEST BEFORE PRODUCTION. Any infrastructure changes, migrations, or configuration modifications recommended by this service must be tested in a non-production environment before deployment. Cloud Intelligence is not liable for outages, data loss, cost overruns, or other damages arising from changes made without adequate testing.',
        'To the maximum extent permitted by applicable law, Cloud Intelligence and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages — including lost revenue, lost savings, data loss, service interruptions, or costs of procurement of substitute services — arising from your use of or reliance on this service, even if advised of the possibility of such damages.',
        'Our total aggregate liability for any claim arising from use of the service shall not exceed the amount you paid us in the 12 months preceding the claim, or $100 USD, whichever is greater.',
      ],
    },
    {
      title: '5. Free Tier',
      body: [
        'The public demo does not offer an enforceable subscription tier or a guaranteed number of AI analyses. AI requests are subject to technical rate limits and service availability.',
        'Paid plans and performance-based billing are not offered through this demo.',
      ],
    },
    {
      title: '6. Paid Services',
      body: [
        'No paid subscription or performance-based billing is offered through this public demo.',
        'Any future paid service would require separate published terms and a verified checkout flow.',
      ],
    },
    {
      title: '7. Acceptable Use',
      body: [
        'You may not use Cloud Intelligence to scrape data, reverse-engineer our models, or resell our output without written permission. Automated access beyond normal use requires a commercial API agreement.',
        'We reserve the right to suspend accounts that we reasonably believe are violating these terms or using the service in a way that harms other users.',
      ],
    },
    {
      title: '8. Changes to Terms',
      body: [
        'These terms may be updated from time to time. Review the current version before using the service.',
        'The current version of these terms is always available at this URL.',
      ],
    },
    {
      title: '9. Governing Law',
      body: [
        'These terms are governed by the laws of the State of Delaware, United States, without regard to conflict of law principles. Any disputes shall be resolved in the courts of Delaware.',
      ],
    },
  ]

  return (
    <div style={{ minHeight: '100vh', background: '#0a0a0f', color: 'white' }}>
      <div style={{ maxWidth: 720, margin: '0 auto', padding: '100px 24px 80px' }}>

        <div style={{ marginBottom: 48 }}>
          <div style={{
            display: 'inline-block',
            background: 'rgba(99,102,241,0.1)',
            border: '1px solid rgba(99,102,241,0.3)',
            borderRadius: 20, padding: '6px 16px',
            fontSize: 12, color: '#818cf8', fontWeight: 700,
            marginBottom: 16, letterSpacing: 1,
          }}>
            LEGAL
          </div>
          <h1 style={{ fontSize: 'clamp(28px, 5vw, 40px)', fontWeight: 900, marginBottom: 12 }}>
            Terms of Service
          </h1>
          <p style={{ color: '#555', fontSize: 14 }}>
            Last updated: May 1, 2026 · Effective immediately for new users
          </p>
        </div>

        <div style={{
          background: 'rgba(245,158,11,0.08)',
          border: '1px solid rgba(245,158,11,0.2)',
          borderRadius: 12, padding: '16px 20px', marginBottom: 48,
        }}>
          <p style={{ fontSize: 14, color: '#fbbf24', margin: 0, lineHeight: 1.6 }}>
            <strong>Plain English summary:</strong> This service gives you AI-powered cloud cost advice.
            It&apos;s advisory only — not a substitute for professional consulting.
            Always verify recommendations before acting. We store your data securely and never sell it.
          </p>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 36 }}>
          {sections.map(section => (
            <div key={section.title}>
              <h2 style={{ fontSize: 17, fontWeight: 800, color: 'white', marginBottom: 14, paddingBottom: 10, borderBottom: '1px solid rgba(255,255,255,0.06)' }}>
                {section.title}
              </h2>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
                {section.body.map((para, i) => (
                  <p key={i} style={{ fontSize: 14, color: '#a0a0b0', lineHeight: 1.75, margin: 0 }}>
                    {para}
                  </p>
                ))}
              </div>
            </div>
          ))}
        </div>

        <div style={{ marginTop: 56, paddingTop: 32, borderTop: '1px solid rgba(255,255,255,0.06)', display: 'flex', gap: 20, flexWrap: 'wrap' }}>
          <a href="/privacy" style={{ color: '#6366f1', fontSize: 14, textDecoration: 'none', fontWeight: 600 }}>
            Privacy Policy →
          </a>
          <a href="mailto:legal@cloudintelligence.ai" style={{ color: '#555', fontSize: 14, textDecoration: 'none' }}>
            Questions? legal@cloudintelligence.ai
          </a>
        </div>
      </div>
    </div>
  )
}
